name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  # Deploy to Raspberry Pi using SSH.
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.RPI_HOST }}
          username: ${{ secrets.RPI_USER }}
          password: ${{ secrets.RPI_SECRET }}
          script: |
            cd /home/fox/256gb_drive/server/apps/winietki_wrss
            git pull origin main
            docker-compose down
            docker-compose up -d --build